<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Serilog.Sinks.InsightIdr</PackageId>
    <Product>Serilog Sinks - Rapid7 IDR</Product>
    <Authors>Chris McKee; Pure Krome (World Domination Technologies)</Authors>
    <Copyright>2019-$([System.DateTime]::Now.Year)</Copyright>
    <Description>A Serilog sink that writes log events to Rapid 7's InsightOps https://docs.rapid7.com/insightidr/insightidr-overview/</Description>
    <PackageProjectUrl>https://github.com/chrismckee/serilog-sinks-insightidr</PackageProjectUrl>
    <PackageTags>serilog logging rapid7 insightops</PackageTags>
    <RepositoryUrl>https://github.com/chrismckee/serilog-sinks-insightidr</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyOriginatorKeyFile>insightidr.snk</AssemblyOriginatorKeyFile>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="../../build/logo.png" Pack="true" Visible="false" PackagePath=""/>
    <None Include="../../README.md" Pack="true" Visible="false" PackagePath=""/>
    <None Include="../../LICENSE" Pack="true" Visible="false" PackagePath=""/>
  </ItemGroup>

</Project>
